export default {
  FONT_SIZE_SMALL: 16,
  FONT_SIZE_MEDIUM: 18,
  FONT_SIZE_LARGE: 12,
  PRIMARY_COLOR: '#ca473c',
  SECONDARY_LIGHT_COLOR: '#ff867c',
  SECONDARY_DARK_COLOR: '#930e15',
  WHITE_COLOR: 'white',
  BLACK_COLOR: 'black',
  FONT_WEIGHT_LIGHT: 200,
  FONT_WEIGHT_MEDIUM: 600,
  FONT_WEIGHT_HEAVY: 800,
};
